# Test environment values
replicaCount: 1

image:
  repository: ghcr.io/svetlioo/java-app
  tag: "1.0.0-2031f36"

env:
  APP_ENVIRONMENT: "test"
  APP_VERSION: "1.0.0"

database:
  host: postgresql-test
  name: appdb_test
  username: appuser_test
  existingSecret: java-app-db-secret

resources:
  limits:
    cpu: 1000m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: false
